# Generated by Django 2.1.1 on 2018-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('isbn', models.CharField(help_text='International Standard Book Number', max_length=17, verbose_name='ISBN')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('authors', models.ManyToManyField(related_name='books', to='authors.Author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ('-created_dt',),
            },
        ),
        migrations.CreateModel(
            name='LogBookAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('prev_title', models.TextField(blank=True, verbose_name='Previous title')),
                ('prev_isbn', models.TextField(blank=True, verbose_name='Previous ISBN')),
                ('prev_price', models.TextField(blank=True, verbose_name='Previous price')),
                ('prev_publish_date', models.TextField(blank=True, verbose_name='Previous publication date')),
                ('title', models.TextField(blank=True, verbose_name='Current title')),
                ('isbn', models.TextField(blank=True, verbose_name='Current ISBN')),
                ('price', models.TextField(blank=True, verbose_name='Current price')),
                ('publish_date', models.TextField(blank=True, verbose_name='Current publication date')),
                ('user', models.TextField(blank=True, verbose_name='Who manipulate book')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('delete', 'Delete'), ('update', 'Update')], default='create', max_length=10, verbose_name='Action type')),
            ],
            options={
                'verbose_name': 'Log book action',
                'verbose_name_plural': 'Log book actions',
                'ordering': ('-created_dt',),
            },
        ),
    ]
