# Generated by Django 2.1.1 on 2018-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('request_method', models.CharField(blank=True, max_length=16, verbose_name='Request method')),
                ('http_host', models.CharField(blank=True, max_length=16, verbose_name='HTTP host')),
                ('http_user_agent', models.TextField(blank=True, verbose_name='HTTP user agent')),
                ('server_protocol', models.CharField(blank=True, max_length=32, verbose_name='Server protocol')),
                ('tz', models.CharField(blank=True, max_length=32, verbose_name='Timezone')),
                ('path_info', models.CharField(blank=True, max_length=64, verbose_name='Path info')),
                ('user', models.CharField(default='Anonymous', max_length=150, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saved request',
                'verbose_name_plural': 'Saved requests',
                'ordering': ('-created_dt',),
            },
        ),
    ]
